# Generated by Django 4.0.7 on 2022-09-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0038_cabling_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='admin_contact',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='noc_contact',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='portal_url',
        ),
    ]
